site_name: Digital Garden
site_description: Digital Garden
site_author: rwxd
site_url: https://wiki.rwxd.eu
dev_addr: 0.0.0.0:8000

repo_name: "wiki"
repo_url: "https://github.com/rwxd/wiki"

docs_dir: "./"
edit_uri: "edit/source/docs/content/"

# https://squidfunk.github.io/mkdocs-material/
theme:
  name: "material"
  palette:
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  icon:
    # logo: material/code-braces-box
    logo: material/pine-tree
  favicon: assets/page/favicon-32x32.png
  language: en
  include_sidebar: true
  features:
    - content.code.annotate
  feature:
    tabs: false
  i18n:
    prev: "Previous"
    next: "Next"
  font:
    text: Inter
    code: Fira Code

copyright: "Copyright &copy; 2021 rwxd"

plugins:
  - search
  - same-dir
  - roamlinks
  - exclude:
      glob:
        - "Readwise/*"
        - "Ignore/*"
        - ".trash/*"
        - ".obsidian/*"
        # - "assets/*"
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
      regex:
        - '.*\.(tmp|bin|tar)$'
  # - awesome-pages:
  #     collapse_single_pages: false

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
      guess_lang: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - toc:
      permalink: "🪴"
  - plantuml_markdown:
      base_dir: src/plantuml/
      format: svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rwxd
