site_name: Wiki
site_description: Wiki
site_author: rwxd
site_url: https://wiki.rwxd.eu
dev_addr: 0.0.0.0:8000

repo_name: "wiki"
repo_url: "https://github.com/rwxd/wiki"

docs_dir: "./"
edit_uri: "edit/source/docs/content/"

# https://squidfunk.github.io/mkdocs-material/
theme:
  name: "material"
  palette:
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  icon:
    # logo: material/code-braces-box
    logo: material/pine-tree
  favicon: assets/page/favicon-96x96.png
  language: en
  include_sidebar: true
  features:
    - content.code.annotate
    - content.code.copy
  feature:
    tabs: false
  i18n:
    prev: "Previous"
    next: "Next"
  font:
    text: Inter
    code: Fira Code

copyright: "Copyright &copy; 2022 rwxd"

plugins:
  - search
  - same-dir
  - roamlinks
  - material-plausible
  - exclude:
      glob:
        - "Readwise/*"
        - "Ignore/*"
        - ".trash/*"
        - ".obsidian/*"
        # - "assets/*"
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
      regex:
        - '.*\.(tmp|bin|tar)$'
  # - awesome-pages:
  #     collapse_single_pages: false

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
      guess_lang: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - toc:
      permalink: "⚑"
  - plantuml_markdown:
      base_dir: src/plantuml/
      format: svg
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rwxd
  analytics:
    provider: plausible
    domain: wiki.rwxd.de
    src: "https://plausible.chaops.de/js/script.js"

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


