# https://taskfile.dev

version: "3"

vars:
  CONTAINER: docker pull ghcr.io/rwxd/wiki-container:main
  CURRENT_DIR:
    sh: pwd
  SITE_DIR: "{{.CURRENT_DIR}}/site"

tasks:
  default:
    cmds:
      - task -l
    silent: true

  serve:
    desc: Serve blog with a container
    vars:
      PORT: 8000
      MOUNT: "{{.CURRENT_DIR}}/src"
    cmds:
      - podman run --rm -p {{.PORT}}:8000 -v ./:/src {{.CONTAINER}} mkdocs serve
    silent: true

  lint:
    desc: Lint markdown
    cmds:
      - podman run --rm {{.CONTAINER}} sh -c "markdownlint --config ../.markdownlint.json docs/"

  build:
    desc: Build blog pages
    cmds:
      - task: lint
      - mkdir -p {{.SITE_DIR}}
      - podman run --rm -v {{.SITE_DIR}}:/src/site {{.CONTAINER}} sh -c "mkdocs build"
      - ls -la
