# https://taskfile.dev

version: "3"

vars:
  CONTAINER: ghcr.io/rwxd/wiki-container:main
  CURRENT_DIR:
    sh: pwd
  SITE_DIR: "{{.CURRENT_DIR}}/site"

tasks:
  default:
    cmds:
      - task -l
    silent: true

  serve:
    desc: Serve blog with a container
    vars:
      PORT: 8000
      MOUNT: "{{.CURRENT_DIR}}/src"
    cmds:
      - podman run --rm -p {{.PORT}}:8000 -v ./:/src {{.CONTAINER}} mkdocs serve
    silent: true

  lint:
    desc: Lint markdown
    cmds:
      - docker run --rm -v {{.CURRENT_DIR}}:/src {{.CONTAINER}} sh -c "markdownlint --config .markdownlint.json docs/"

  build:
    desc: Build blog pages
    cmds:
      - task: lint
      - mkdir -p {{.SITE_DIR}}
      - docker run --rm -v {{.CURRENT_DIR}}:/src {{.CONTAINER}} sh -c "mkdocs build"
      - ls -la
